const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

// Resolve paths relative to the backend root (parent of scripts/)
const Product = require(path.join(__dirname, '..', 'models', 'Product'));
const User = require(path.join(__dirname, '..', 'models', 'User'));
const connectDB = require(path.join(__dirname, '..', 'config', 'db'));
const bcrypt = require('bcryptjs');

// Load .env from the backend root
dotenv.config({ path: path.join(__dirname, '..', '.env') });

// Import new product data
const { newElectronics, newFootwear, newClothing } = require(path.join(__dirname, '..', 'data', 'newProducts'));
const { newAccessories, newFurniture, newSports } = require(path.join(__dirname, '..', 'data', 'newProducts2'));
const { newHomeKitchen, newStationery, newBooksMedia, newBeauty } = require(path.join(__dirname, '..', 'data', 'newProducts3'));
const { newToysGames, newAutomotive } = require(path.join(__dirname, '..', 'data', 'newProducts4'));

connectDB();

const products = [
    // Electronics (10)
    { title: 'Apple iPhone 15 Pro', price: 129999, category: 'Electronics', image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', rating: { rate: 4.9, count: 450 }, description: 'Titanium design with A17 Pro chip, 48MP camera, and USB-C. Features Action button and customizable always-on display.', sizes: ['128GB', '256GB', '512GB'], stock: 75, features: ['A17 Pro Chip', 'Titanium Build', '48MP Camera', 'Action Button'] },
    { title: 'Samsung Galaxy S24 Ultra', price: 124999, category: 'Electronics', image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800', rating: { rate: 4.8, count: 320 }, description: 'AI-powered Galaxy phone with S-Pen, 200MP camera, and titanium frame. Circle to Search and Live Translate built-in.', sizes: ['256GB', '512GB'], stock: 60, features: ['Galaxy AI', 'S-Pen', '200MP Camera', 'Circle to Search'] },
    { title: 'Sony WH-1000XM5', price: 29999, category: 'Electronics', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800', rating: { rate: 4.9, count: 850 }, description: 'Industry-leading noise cancelling headphones with 30-hour battery, multipoint connectivity, and speak-to-chat.', sizes: [], stock: 140, features: ['ANC Leader', '30hr Battery', 'Multipoint', 'Speak-to-Chat'] },
    { title: 'MacBook Air M3', price: 114999, category: 'Electronics', image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800', rating: { rate: 4.8, count: 120 }, description: 'Ultra-thin laptop with M3 chip, 18-hour battery life, Liquid Retina display, and fanless silent operation.', sizes: ['8GB', '16GB'], stock: 45, features: ['M3 Chip', '18hr Battery', 'Liquid Retina', 'Fanless'] },
    { title: 'PlayStation 5', price: 54999, category: 'Electronics', image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800', rating: { rate: 4.9, count: 2100 }, description: 'Next-gen gaming console with 4K/120fps, ray tracing, haptic feedback DualSense controller, and ultra-fast SSD.', sizes: ['Disc Edition'], stock: 35, features: ['4K/120fps', 'Ray Tracing', 'DualSense', 'Ultra-Fast SSD'] },
    { title: 'Dell XPS 13', price: 95000, category: 'Electronics', image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800', rating: { rate: 4.6, count: 95 }, description: 'Premium ultrabook with InfinityEdge display, 12th Gen Intel Core, and CNC machined aluminum chassis.', sizes: ['16GB RAM'], stock: 28, features: ['InfinityEdge', 'CNC Aluminum', '12th Gen Intel', 'Thunderbolt 4'] },
    { title: 'LG OLED TV', price: 135000, category: 'Electronics', image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800', rating: { rate: 4.9, count: 300 }, description: '4K OLED evo with self-lit pixels, Dolby Vision IQ, α9 AI processor, and VRR gaming support.', sizes: ['55-inch'], stock: 15, features: ['OLED evo', 'Dolby Vision IQ', 'α9 AI Chip', 'VRR Gaming'] },
    { title: 'Canon R5 Camera', price: 320000, category: 'Electronics', image: 'https://images.unsplash.com/photo-1519183071298-a2962feb14f4?w=800', rating: { rate: 4.8, count: 45 }, description: 'Professional mirrorless camera with 45MP full-frame sensor, 8K RAW video, and Dual Pixel CMOS AF II.', sizes: [], stock: 8, features: ['45MP Sensor', '8K RAW Video', 'Dual Pixel AF', 'In-Body IS'] },
    { title: 'Nintendo Switch', price: 32999, category: 'Electronics', image: 'https://images.unsplash.com/photo-1618519764620-7403abdbdfe9?w=800', rating: { rate: 4.7, count: 1500 }, description: 'Versatile gaming console with detachable Joy-Cons, 3 play modes, and massive game library.', sizes: [], stock: 100, features: ['3 Play Modes', 'Joy-Con Controllers', 'Portable', 'Game Library'] },
    { title: 'Apple Watch S9', price: 41900, category: 'Electronics', image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800', rating: { rate: 4.8, count: 500 }, description: 'Advanced health smartwatch with blood oxygen sensor, ECG, crash detection, and double-tap gesture.', sizes: ['41mm', '45mm'], stock: 90, features: ['Blood O2 Sensor', 'ECG', 'Crash Detection', 'Double-Tap'] },

    // Footwear (10)
    { title: 'Nike Air Jordan', price: 8995, category: 'Footwear', image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800', rating: { rate: 4.9, count: 1200 }, description: 'Iconic high-top basketball shoe with Air cushioning, leather upper, and padded collar for ankle support.', sizes: ['8', '9', '10'], stock: 65, features: ['Air Cushioning', 'Leather Upper', 'Padded Collar', 'Iconic Design'] },
    { title: 'Nike Air Max', price: 13995, category: 'Footwear', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', rating: { rate: 4.8, count: 2500 }, description: 'Max Air cushioning sneaker with visible Air unit, mesh upper, and rubber waffle outsole for traction.', sizes: ['9', '10'], stock: 80, features: ['Visible Air Unit', 'Waffle Outsole', 'Mesh Upper', 'Max Cushion'] },
    { title: 'Adidas Ultraboost', price: 18999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800', rating: { rate: 4.7, count: 800 }, description: 'Responsive running shoe with Boost midsole, Primeknit upper, and Continental rubber outsole grip.', sizes: ['8', '9'], stock: 55, features: ['Boost Midsole', 'Primeknit', 'Continental Rubber', 'Responsive'] },
    { title: 'Adidas Stan Smith', price: 8999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1588099768531-a72d4a198538?w=800', rating: { rate: 4.6, count: 3200 }, description: 'Classic minimalist white leather tennis shoe with perforated 3-Stripes and green heel tab.', sizes: ['7', '8'], stock: 120, features: ['Leather Upper', 'Perforated Stripes', 'Green Heel Tab', 'Tennis Classic'] },
    { title: 'Puma RS-X', price: 7999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', rating: { rate: 4.5, count: 450 }, description: 'Chunky retro-inspired running sneaker with RS cushioning, bold colorblock design, and mesh panels.', sizes: ['8', '9'], stock: 95, features: ['RS Cushioning', 'Retro Chunky', 'Colorblock', 'Mesh Panels'] },
    { title: 'Puma Suede', price: 6999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800', rating: { rate: 4.4, count: 1500 }, description: 'Heritage suede sneaker in classic blue with formstrip, rubber cupsole, and padded tongue.', sizes: ['7', '8'], stock: 110, features: ['Suede Upper', 'Formstrip', 'Cupsole', 'Heritage Design'] },
    { title: 'Reebok Nano', price: 11999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800', rating: { rate: 4.8, count: 220 }, description: 'CrossFit training shoe with Flexweave upper, heel clip for stability, and low-cut design for mobility.', sizes: ['9', '10'], stock: 70, features: ['Flexweave', 'Heel Clip', 'CrossFit Ready', 'Low-Cut'] },
    { title: 'Reebok Classic', price: 7999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800', rating: { rate: 4.7, count: 560 }, description: 'Timeless leather sneaker in black with die-cut EVA midsole, padded foam sockliner, and high-abrasion outsole.', sizes: ['8', '10'], stock: 100, features: ['Full-Grain Leather', 'EVA Midsole', 'Sockliner', 'Classic'] },
    { title: 'Nike Dunk', price: 11995, category: 'Footwear', image: 'https://images.unsplash.com/photo-1628253747716-0c4f5c90fdda?w=800', rating: { rate: 4.9, count: 4000 }, description: 'Retro low-top basketball shoe with premium leather, foam midsole, and perforated toe box for breathability.', sizes: ['8', '9'], stock: 40, features: ['Premium Leather', 'Foam Midsole', 'Perforated Toe', 'Retro Style'] },
    { title: 'Adidas Samba', price: 10999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800', rating: { rate: 4.8, count: 1800 }, description: 'Terrace-style black leather shoe with gum rubber sole, suede T-toe overlay, and gold foil branding.', sizes: ['7', '9'], stock: 85, features: ['Gum Sole', 'Suede T-Toe', 'Gold Foil', 'Terrace Style'] },

    // Clothing (10)
    { title: 'Denim Jeans', price: 4599, category: 'Clothing', image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', rating: { rate: 4.6, count: 1200 }, description: 'Raw selvedge denim jeans with natural indigo dye, copper rivets, and slim tapered fit.', sizes: ['32', '34'], stock: 90, features: ['Selvedge Denim', 'Natural Indigo', 'Copper Rivets', 'Slim Tapered'] },
    { title: 'Cotton Tee', price: 1490, category: 'Clothing', image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800', rating: { rate: 4.8, count: 500 }, description: 'Ultra-soft Supima cotton crew neck t-shirt with reinforced seams and pre-shrunk fabric.', sizes: ['M', 'L'], stock: 200, features: ['Supima Cotton', 'Pre-Shrunk', 'Reinforced Seams', 'Crew Neck'] },
    { title: 'Biker Jacket', price: 9999, category: 'Clothing', image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800', rating: { rate: 4.5, count: 85 }, description: 'Premium faux leather biker jacket with asymmetric zip, snap-down collar, and quilted lining.', sizes: ['L', 'XL'], stock: 35, features: ['Faux Leather', 'Asymmetric Zip', 'Quilted Lining', 'Snap Collar'] },
    { title: 'Casual Shirt', price: 2299, category: 'Clothing', image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800', rating: { rate: 4.3, count: 150 }, description: 'Breathable linen shirt in sage green with mother-of-pearl buttons and relaxed fit.', sizes: ['M', 'L'], stock: 130, features: ['Pure Linen', 'Pearl Buttons', 'Relaxed Fit', 'Sage Green'] },
    { title: 'Winter Puffer', price: 24999, category: 'Clothing', image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800', rating: { rate: 4.9, count: 320 }, description: 'Insulated puffer jacket with 700-fill-power goose down, water-repellent shell, and packable design.', sizes: ['S', 'M'], stock: 25, features: ['700-Fill Down', 'Water-Repellent', 'Packable', 'Insulated'] },
    { title: 'Running Tights', price: 3495, category: 'Clothing', image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800', rating: { rate: 4.7, count: 450 }, description: 'Compression running tights with moisture-wicking DRI-FIT fabric, reflective elements, and zip pocket.', sizes: ['M', 'L'], stock: 115, features: ['DRI-FIT', 'Compression', 'Reflective', 'Zip Pocket'] },
    { title: 'Mesh Polo', price: 8900, category: 'Clothing', image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800', rating: { rate: 4.6, count: 560 }, description: 'Classic navy mesh polo with signature embroidered logo, ribbed collar, and two-button placket.', sizes: ['M', 'L'], stock: 145, features: ['Mesh Fabric', 'Embroidered Logo', 'Ribbed Collar', 'Classic Navy'] },
    { title: 'Cotton Hoodie', price: 7999, category: 'Clothing', image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800', rating: { rate: 4.7, count: 110 }, description: 'Heavyweight 400gsm cotton fleece hoodie with kangaroo pocket, ribbed cuffs, and drawstring hood.', sizes: ['M', 'L'], stock: 80, features: ['400gsm Fleece', 'Kangaroo Pocket', 'Ribbed Cuffs', 'Heavyweight'] },
    { title: 'Sport Shorts', price: 1999, category: 'Clothing', image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800', rating: { rate: 4.4, count: 210 }, description: 'Lightweight training shorts with internal liner, four-way stretch, and quick-dry technology.', sizes: ['L', 'XL'], stock: 175, features: ['Quick-Dry', '4-Way Stretch', 'Internal Liner', 'Lightweight'] },
    { title: 'Formal Suit', price: 65000, category: 'Clothing', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800', rating: { rate: 4.8, count: 42 }, description: 'Charcoal grey Italian wool suit with half-canvas construction, surgeon cuffs, and slim-modern fit.', sizes: ['42R'], stock: 12, features: ['Italian Wool', 'Half-Canvas', 'Surgeon Cuffs', 'Slim-Modern'] },

    // Accessories (10)
    { title: 'Wayfarer Shades', price: 12490, category: 'Accessories', image: 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=800', rating: { rate: 4.8, count: 950 }, description: 'Classic tortoise shell wayfarer sunglasses with polarized lenses and spring-loaded hinges.', sizes: [], stock: 130, features: ['Polarized', 'Tortoise Shell', 'Spring Hinges', 'UV Protection'] },
    { title: 'Signature Pen', price: 45000, category: 'Accessories', image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800', rating: { rate: 4.9, count: 200 }, description: 'Luxury chrome nib fountain pen with 18K gold plating, piston fill mechanism, and presentation box.', sizes: [], stock: 20, features: ['18K Gold Plating', 'Chrome Nib', 'Piston Fill', 'Presentation Box'] },
    { title: 'Urban Backpack', price: 10999, category: 'Accessories', image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', rating: { rate: 4.7, count: 1800 }, description: 'Water-resistant polyester backpack with padded laptop compartment, hidden anti-theft pocket, and USB port.', sizes: [], stock: 155, features: ['Water-Resistant', 'Anti-Theft', 'USB Port', 'Laptop Padded'] },
    { title: 'Leather Wallet', price: 3495, category: 'Accessories', image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800', rating: { rate: 4.5, count: 560 }, description: 'Full-grain tan leather bifold wallet with RFID protection and 8 card slots plus coin pocket.', sizes: [], stock: 180, features: ['Full-Grain Leather', 'RFID Protection', '8 Card Slots', 'Coin Pocket'] },
    { title: 'Sport G-Shock', price: 9495, category: 'Accessories', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', rating: { rate: 4.8, count: 1200 }, description: 'Shock-resistant digital watch with 200m water resistance, world time, and solar-powered battery.', sizes: [], stock: 95, features: ['200m Water Resist', 'Solar Powered', 'World Time', 'Shock Resist'] },
    { title: 'Floral Scarf', price: 35000, category: 'Accessories', image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800', rating: { rate: 4.6, count: 45 }, description: 'Hand-printed pink silk scarf with rolled edges, 90x90cm square format, and signature motif.', sizes: [], stock: 22, features: ['Pure Silk', 'Hand-Printed', 'Rolled Edges', 'Signature Motif'] },
    { title: 'AirTag 4pk', price: 11900, category: 'Accessories', image: 'https://images.unsplash.com/photo-1617042375876-a13e36732a04?w=800', rating: { rate: 4.8, count: 2500 }, description: 'Apple precision finding trackers with UWB chip, Find My network, and replaceable CR2032 battery.', sizes: [], stock: 160, features: ['UWB Chip', 'Find My Network', 'Precision Finding', 'Replaceable Battery'] },
    { title: 'Tumi Case', price: 75000, category: 'Accessories', image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800', rating: { rate: 4.9, count: 120 }, description: 'Hard shell carry-on with ballistic nylon, Tumi Tracer ID, integrated TSA lock, and 360° wheels.', sizes: [], stock: 18, features: ['Ballistic Nylon', 'Tumi Tracer', 'TSA Lock', '360° Wheels'] },
    { title: 'Oakley Radar', price: 10990, category: 'Accessories', image: 'https://images.unsplash.com/photo-1614715838608-dd527c46231d?w=800', rating: { rate: 4.7, count: 450 }, description: 'Sport cycling sunglasses with Prizm Road lens technology, O-Matter frame, and Unobtainium grip.', sizes: [], stock: 75, features: ['Prizm Road Lens', 'O-Matter Frame', 'Unobtainium Grip', 'Sport Fit'] },
    { title: 'Secrid Wallet', price: 5995, category: 'Accessories', image: 'https://images.unsplash.com/photo-1632516643720-e7f5d7d6ecc9?w=800', rating: { rate: 4.8, count: 320 }, description: 'Compact aluminum card case with RFID-safe cardprotector, leather sleeve, and pop-up mechanism.', sizes: [], stock: 110, features: ['RFID-Safe', 'Pop-Up Mechanism', 'Aluminum Case', 'Leather Sleeve'] },

    // Furniture (10)
    { title: 'Armchair Grey', price: 8990, category: 'Furniture', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', rating: { rate: 4.5, count: 2500 }, description: 'Bentwood accent armchair with woven grey upholstery, curved frame, and natural finish legs.', sizes: [], stock: 45, features: ['Bentwood Frame', 'Woven Upholstery', 'Curved Design', 'Natural Finish'] },
    { title: 'Velvet Sofa', price: 125000, category: 'Furniture', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800', rating: { rate: 4.8, count: 85 }, description: 'Emerald green velvet sofa with channel tufting, solid wood frame, and tapered brass legs.', sizes: ['3st'], stock: 8, features: ['Channel Tufted', 'Brass Legs', 'Solid Wood Frame', 'Emerald Velvet'] },
    { title: 'Aeron Office', price: 155000, category: 'Furniture', image: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800', rating: { rate: 4.9, count: 1200 }, description: 'Iconic ergonomic mesh office chair with PostureFit SL, 8Z Pellicle suspension, and 12-year warranty.', sizes: ['B'], stock: 15, features: ['PostureFit SL', '8Z Pellicle', '12-Year Warranty', 'Iconic Ergonomic'] },
    { title: 'Oak Table', price: 45000, category: 'Furniture', image: 'https://images.unsplash.com/photo-1577146371523-d9d2cd5816da?w=800', rating: { rate: 4.7, count: 42 }, description: 'Solid oak rectangular dining table with live edge detail, seats 6, and matte lacquer finish.', sizes: ['6st'], stock: 10, features: ['Live Edge', 'Solid Oak', 'Seats 6', 'Matte Lacquer'] },
    { title: 'King Bed', price: 38000, category: 'Furniture', image: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800', rating: { rate: 4.6, count: 110 }, description: 'Upholstered king-size bed with fabric headboard, sprung slat base, and under-bed storage.', sizes: ['K'], stock: 12, features: ['Storage Base', 'Sprung Slats', 'Fabric Headboard', 'King Size'] },
    { title: 'Steel Shelf', price: 12000, category: 'Furniture', image: 'https://images.unsplash.com/photo-1594620302200-9a7621ef6ef7?w=800', rating: { rate: 4.4, count: 67 }, description: 'Industrial 5-tier steel shelving unit with powder-coated finish, adjustable shelves, and wall mount option.', sizes: [], stock: 85, features: ['5-Tier', 'Powder-Coated', 'Adjustable', 'Wall Mount'] },
    { title: 'Marble Side', price: 15999, category: 'Furniture', image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800', rating: { rate: 4.7, count: 35 }, description: 'Round marble-top side table with brushed gold hairpin legs and natural veining.', sizes: [], stock: 30, features: ['Real Marble', 'Gold Hairpin Legs', 'Natural Veining', 'Round Top'] },
    { title: 'Leather Foot', price: 7999, category: 'Furniture', image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800', rating: { rate: 4.5, count: 120 }, description: 'Tufted leather ottoman with hidden storage, solid wood frame, and button detailing.', sizes: [], stock: 65, features: ['Hidden Storage', 'Tufted Leather', 'Button Detail', 'Solid Wood'] },
    { title: 'TV Wall Unit', price: 14500, category: 'Furniture', image: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=800', rating: { rate: 4.6, count: 92 }, description: 'Modern floating TV wall unit with LED ambient lighting, cable management, and soft-close drawers.', sizes: [], stock: 38, features: ['LED Ambient Light', 'Cable Management', 'Soft-Close', 'Floating Mount'] },
    { title: 'Stand Desk', price: 22000, category: 'Furniture', image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800', rating: { rate: 4.7, count: 156 }, description: 'Motorized sit-stand desk with dual motors, memory presets, and anti-collision technology.', sizes: [], stock: 42, features: ['Dual Motors', 'Memory Presets', 'Anti-Collision', 'Motorized'] },

    // Sports (10)
    { title: 'NBA Ball', price: 2499, category: 'Sports', image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800', rating: { rate: 4.8, count: 4500 }, description: 'Official size composite leather basketball with deep channel design and moisture-absorbing cover.', sizes: [], stock: 160, features: ['Official Size', 'Composite Leather', 'Deep Channels', 'Moisture-Absorbing'] },
    { title: 'Pro Racket', price: 16900, category: 'Sports', image: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800', rating: { rate: 4.9, count: 120 }, description: 'Professional tennis racket with stiff graphite frame, string dampener, and control-oriented head pattern.', sizes: [], stock: 35, features: ['Graphite Frame', 'Control Head', 'String Dampener', 'Professional'] },
    { title: 'Weights Pod', price: 35000, category: 'Sports', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800', rating: { rate: 4.7, count: 320 }, description: 'Neoprene-coated dumbbell pod set with ergonomic grip, anti-roll design, and storage stand included.', sizes: [], stock: 28, features: ['Neoprene Coated', 'Anti-Roll', 'Ergonomic Grip', 'Stand Included'] },
    { title: 'Grip Mat', price: 6500, category: 'Sports', image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800', rating: { rate: 4.8, count: 1500 }, description: 'Non-slip natural rubber yoga mat with alignment lines and eco-friendly biodegradable surface.', sizes: [], stock: 135, features: ['Natural Rubber', 'Alignment Lines', 'Eco-Friendly', 'Non-Slip'] },
    { title: 'Cycling Lid', price: 8900, category: 'Sports', image: 'https://images.unsplash.com/photo-1557844352-761f2565b576?w=800', rating: { rate: 4.6, count: 450 }, description: 'Aerodynamic cycling helmet with MIPS protection, adjustable fit system, and integrated visor.', sizes: [], stock: 70, features: ['MIPS Protection', 'Aero Design', 'Adjustable Fit', 'Integrated Visor'] },
    { title: 'Wilson Pro', price: 19500, category: 'Sports', image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800', rating: { rate: 4.9, count: 200 }, description: 'Competition-grade graphite badminton racket with nano-carbon shaft and isometric head shape.', sizes: [], stock: 48, features: ['Graphite Build', 'Nano-Carbon Shaft', 'Isometric Head', 'Competition'] },
    { title: 'Everlast 12', price: 3599, category: 'Sports', image: 'https://images.unsplash.com/photo-1583473848882-f9a5bc7fd2ee?w=800', rating: { rate: 4.5, count: 1800 }, description: 'Premium 12oz boxing gloves with multi-layer foam padding, hook-and-loop wrist closure, and thumb lock.', sizes: [], stock: 100, features: ['Multi-Layer Foam', 'Hook-Loop Closure', 'Thumb Lock', '12oz Pro'] },
    { title: 'Swim Vision', price: 1899, category: 'Sports', image: 'https://images.unsplash.com/photo-1530549387789-4c1017266636?w=800', rating: { rate: 4.4, count: 2500 }, description: 'Anti-fog mirror lens swim goggles with UV protection, adjustable nose bridge, and silicone gaskets.', sizes: [], stock: 190, features: ['Mirror Lens', 'Anti-Fog', 'UV Protection', 'Silicone Gasket'] },
    { title: 'Magnum Bat', price: 28000, category: 'Sports', image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800', rating: { rate: 4.8, count: 150 }, description: 'Grade 1 English willow cricket bat with mid-low sweet spot, round handle, and traditional profile.', sizes: [], stock: 20, features: ['Grade 1 Willow', 'English Made', 'Mid-Low Sweet Spot', 'Round Handle'] },
    { title: 'Fitbit Sync', price: 14999, category: 'Sports', image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800', rating: { rate: 4.6, count: 800 }, description: 'Smart fitness tracker with continuous heart rate, sleep tracking, GPS, and 7-day battery life.', sizes: [], stock: 88, features: ['Heart Rate', 'Sleep Tracking', 'GPS Built-In', '7-Day Battery'] },

    // Home & Kitchen (10)
    { title: 'Air Fry XL', price: 16995, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?w=800', rating: { rate: 4.8, count: 3200 }, description: 'Dual-zone air fryer with smart finish technology, 8-quart capacity, and one-touch presets.', sizes: [], stock: 110, features: ['Dual-Zone', 'Smart Finish', '8-Quart', 'One-Touch Presets'] },
    { title: 'Espresso Bar', price: 21000, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=800', rating: { rate: 4.7, count: 1100 }, description: 'Semi-automatic espresso machine with steam wand, 15-bar pressure, PID temperature control, and portafilter.', sizes: [], stock: 35, features: ['15-Bar Pressure', 'PID Temp Control', 'Steam Wand', 'Portafilter'] },
    { title: 'Stand Mixer', price: 45000, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=800', rating: { rate: 4.9, count: 5600 }, description: 'Professional stand mixer with 5-quart stainless bowl, 10 speeds, planetary mixing action, and tilt-head design.', sizes: [], stock: 50, features: ['10 Speeds', 'Planetary Action', 'Tilt-Head', '5-Qt Bowl'] },
    { title: 'Cast Iron Pot', price: 32000, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', rating: { rate: 4.8, count: 1500 }, description: 'Heavy-duty enameled cast iron Dutch oven with self-basting lid spikes and even heat distribution.', sizes: [], stock: 40, features: ['Self-Basting', 'Cast Iron', 'Enamel Coated', 'Even Heat'] },
    { title: 'Dyson Vac', price: 65000, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800', rating: { rate: 4.9, count: 450 }, description: 'Cordless stick vacuum with powerful suction, HEPA filtration, LCD screen, and up to 60 minutes runtime.', sizes: [], stock: 22, features: ['Cordless', 'HEPA Filter', 'LCD Screen', '60min Runtime'] },
    { title: 'Steel Knives', price: 18000, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800', rating: { rate: 4.7, count: 320 }, description: 'German stainless steel knife set with razor-sharp edge, forged bolster, and magnetic block.', sizes: [], stock: 55, features: ['German Steel', 'Forged Bolster', 'Magnetic Block', 'Razor-Sharp'] },
    { title: 'Staub Pot', price: 28000, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=800', rating: { rate: 4.8, count: 850 }, description: 'French-made enameled cast iron cocotte with self-basting spikes, black matte interior, and nickel knob.', sizes: [], stock: 30, features: ['French-Made', 'Matte Interior', 'Nickel Knob', 'Self-Basting'] },
    { title: 'Grill Skillet', price: 3999, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=800', rating: { rate: 4.6, count: 12000 }, description: 'Cast iron square grill pan with raised ridges for searing, pre-seasoned coating, and dual pour spouts.', sizes: [], stock: 150, features: ['Pre-Seasoned', 'Raised Ridges', 'Pour Spouts', 'Cast Iron'] },
    { title: 'Fresh Storage', price: 2500, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1627483297929-37f416fec7cd?w=800', rating: { rate: 4.5, count: 6500 }, description: 'BPA-free food storage set with snap-lock lids, stackable design, and freezer/microwave/dishwasher safe.', sizes: [], stock: 200, features: ['BPA-Free', 'Snap-Lock', 'Stackable', 'Multi-Safe'] },
    { title: 'Pro Cooker', price: 14500, category: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800', rating: { rate: 4.8, count: 8200 }, description: 'Smart pressure cooker with digital display, 12 preset programs, delay timer, and keep-warm function.', sizes: [], stock: 95, features: ['12 Presets', 'Delay Timer', 'Keep-Warm', 'Digital Display'] },

    // Stationery (10)
    { title: 'Classic Note', price: 2295, category: 'Stationery', image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800', rating: { rate: 4.7, count: 3500 }, description: 'Hardcover ruled notebook with elastic closure, expandable inner pocket, and acid-free ivory paper.', sizes: [], stock: 180, features: ['Elastic Closure', 'Inner Pocket', 'Acid-Free Paper', 'Hardcover'] },
    { title: 'Safari Pen', price: 2800, category: 'Stationery', image: 'https://images.unsplash.com/photo-1562240020-ce31ccb0fa7d?w=800', rating: { rate: 4.8, count: 1500 }, description: 'Ergonomic fountain pen with triangular grip, steel nib, and snap-on cap. Includes ink cartridge.', sizes: [], stock: 120, features: ['Triangular Grip', 'Steel Nib', 'Snap-On Cap', 'Ink Included'] },
    { title: 'Digital Tablet', price: 8999, category: 'Stationery', image: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=800', rating: { rate: 4.6, count: 1100 }, description: 'Graphics drawing tablet with 8192 pressure levels, battery-free stylus, and customizable express keys.', sizes: [], stock: 55, features: ['8192 Levels', 'Battery-Free Stylus', 'Express Keys', 'Drawing Pro'] },
    { title: 'Click Pen', price: 850, category: 'Stationery', image: 'https://images.unsplash.com/photo-1625935228908-e7eda1a48f49?w=800', rating: { rate: 4.5, count: 8500 }, description: 'Iconic retractable ballpoint with low-viscosity ink, stainless steel tip, and comfortable rubber grip.', sizes: [], stock: 250, features: ['Low-Viscosity Ink', 'Steel Tip', 'Rubber Grip', 'Retractable'] },
    { title: 'Neon Set', price: 950, category: 'Stationery', image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800', rating: { rate: 4.8, count: 12000 }, description: 'Set of 6 gel neon highlighters with chisel tip, smear-guard ink, and translucent barrel.', sizes: [], stock: 300, features: ['6 Colors', 'Chisel Tip', 'Smear-Guard', 'Gel Highlighter'] },
    { title: 'Pencil Case', price: 3500, category: 'Stationery', image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800', rating: { rate: 4.7, count: 2500 }, description: 'Premium tin pencil case with embossed lid, hinged opening, and compartments for 36 pencils.', sizes: [], stock: 140, features: ['Embossed Tin', 'Hinged Opening', '36-Pencil Capacity', 'Premium'] },
    { title: 'Desktop Pad', price: 995, category: 'Stationery', image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800', rating: { rate: 4.9, count: 3200 }, description: 'Large desk mat pad in cork-leather hybrid with non-slip backing and waterproof surface.', sizes: [], stock: 190, features: ['Cork-Leather', 'Non-Slip', 'Waterproof', 'Large Size'] },
    { title: 'Super Tips', price: 1200, category: 'Stationery', image: 'https://images.unsplash.com/photo-1516962080544-eac695c93791?w=800', rating: { rate: 4.6, count: 7500 }, description: 'Washable marker set with flexible felt tips, non-toxic formula, and won\'t dry out if uncapped for 24hrs.', sizes: [], stock: 210, features: ['Washable', 'Flexible Tips', 'Non-Toxic', '24hr Cap-Off'] },
    { title: 'Fine Write', price: 1450, category: 'Stationery', image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800', rating: { rate: 4.7, count: 5600 }, description: 'Precision 0.5mm gel pen with needle-point tip, waterproof pigment ink, and transparent barrel.', sizes: [], stock: 170, features: ['0.5mm Tip', 'Waterproof Ink', 'Needle-Point', 'Pigment Ink'] },
    { title: 'Sticky Set', price: 650, category: 'Stationery', image: 'https://images.unsplash.com/photo-1579017308347-e53e0d2fc5e9?w=800', rating: { rate: 4.8, count: 15000 }, description: 'Super sticky note pack in yellow and pink with Canary adhesive, 3x3 inch, and 100 sheets per pad.', sizes: [], stock: 350, features: ['Super Sticky', 'Canary Adhesive', '100 Sheets', 'Dual Color'] },

    // Books & Media (10)
    { title: 'Atomic Habits', price: 599, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800', rating: { rate: 4.9, count: 85000 }, description: 'James Clear\'s groundbreaking guide to building good habits and breaking bad ones through tiny changes.', sizes: [], stock: 350, features: ['Habit Building', 'Bestseller', 'Self-Help', 'Tiny Changes'] },
    { title: 'Psychology Money', price: 450, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800', rating: { rate: 4.8, count: 32000 }, description: 'Morgan Housel explores the strange ways people think about money through 19 short stories.', sizes: [], stock: 280, features: ['Financial Literacy', '19 Stories', 'Psychology', 'Bestseller'] },
    { title: 'Kindle Fire', price: 14999, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d7?w=800', rating: { rate: 4.8, count: 15000 }, description: 'HD tablet with 10.1-inch screen, Alexa hands-free, and access to millions of books, apps, and games.', sizes: [], stock: 85, features: ['10.1-inch HD', 'Alexa Built-In', 'Millions of Apps', 'Hands-Free'] },
    { title: 'The Alchemist', price: 350, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800', rating: { rate: 4.7, count: 120000 }, description: 'Paulo Coelho\'s enchanting novel about following your dreams. Translated into 80 languages worldwide.', sizes: [], stock: 400, features: ['80 Languages', 'Classic Novel', 'Inspirational', 'Dream Quest'] },
    { title: 'Creative Act', price: 1800, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=800', rating: { rate: 4.9, count: 5600 }, description: 'Rick Rubin\'s guide to creativity that applies to all disciplines, not just music. A beautiful exploration.', sizes: [], stock: 90, features: ['Creativity', 'Rick Rubin', 'All Disciplines', 'Exploration'] },
    { title: 'Ikigai Secret', price: 499, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1517502474097-f9b30659dadb?w=800', rating: { rate: 4.6, count: 45000 }, description: 'The Japanese secret to a long and happy life. Explores the concept of finding your purpose.', sizes: [], stock: 220, features: ['Japanese Wisdom', 'Purpose', 'Longevity', 'Happiness'] },
    { title: 'Sapiens History', price: 650, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=800', rating: { rate: 4.8, count: 75000 }, description: 'Yuval Noah Harari\'s sweeping account of humankind from the Stone Age to the Silicon Age.', sizes: [], stock: 185, features: ['World History', 'Harari', 'Stone to Silicon', 'Thought-Provoking'] },
    { title: 'Grow Rich', price: 299, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800', rating: { rate: 4.5, count: 110000 }, description: 'Napoleon Hill\'s timeless classic on the philosophy of success, based on 20 years of research.', sizes: [], stock: 320, features: ['Success Philosophy', '20yr Research', 'Classic', 'Timeless'] },
    { title: 'Search Meaning', price: 399, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1592492159418-39f319320569?w=800', rating: { rate: 4.9, count: 65000 }, description: 'Viktor Frankl\'s memoir of finding meaning in the Nazi concentration camps. A masterpiece of logotherapy.', sizes: [], stock: 250, features: ['Memoir', 'Logotherapy', 'Holocaust', 'Meaning of Life'] },
    { title: 'ZeroToOne', price: 550, category: 'Books & Media', image: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800', rating: { rate: 4.7, count: 18000 }, description: 'Peter Thiel\'s notes on startups, monopolies, and building the future. Contrarian thinking at its best.', sizes: [], stock: 140, features: ['Startups', 'Peter Thiel', 'Contrarian', 'Future Building'] },

    // Beauty & Personal Care (10)
    { title: 'Hydra Clean', price: 1550, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800', rating: { rate: 4.8, count: 25000 }, description: 'Gentle hydrating cleanser with hyaluronic acid, ceramides, and non-stripping formula for all skin types.', sizes: [], stock: 200, features: ['Hyaluronic Acid', 'Ceramides', 'Non-Stripping', 'All Skin Types'] },
    { title: 'Blemish Serum', price: 750, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800', rating: { rate: 4.6, count: 45000 }, description: 'Niacinamide 10% + zinc 1% serum for blemish control, pore minimizing, and oil balance.', sizes: [], stock: 250, features: ['10% Niacinamide', 'Zinc 1%', 'Pore Minimizing', 'Oil Control'] },
    { title: 'SPF 50 Gel', price: 2450, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800', rating: { rate: 4.9, count: 12000 }, description: 'Lightweight SPF 50 PA++++ sunscreen gel with no white cast, water-resistant, and sebum control.', sizes: [], stock: 180, features: ['SPF 50 PA++++', 'No White Cast', 'Water-Resistant', 'Sebum Control'] },
    { title: 'Night Recovery', price: 8500, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800', rating: { rate: 4.8, count: 8500 }, description: 'Advanced night repair serum with ChronoluxCB technology, hyaluronic acid, and synchronized recovery complex.', sizes: [], stock: 45, features: ['ChronoluxCB', 'Night Repair', 'Hyaluronic Acid', 'Anti-Aging'] },
    { title: 'Hair Volume', price: 4999, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800', rating: { rate: 4.5, count: 320000 }, description: 'Professional ionic hair dryer with 1875W motor, concentrator nozzles, and cold shot for setting styles.', sizes: [], stock: 85, features: ['1875W Motor', 'Ionic Tech', 'Cold Shot', 'Concentrator Nozzles'] },
    { title: 'Elite Scent', price: 14500, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800', rating: { rate: 4.9, count: 4500 }, description: 'Eau de Parfum with notes of bergamot, ambroxan, and patchouli. Long-lasting 12-hour projection.', sizes: [], stock: 55, features: ['12hr Projection', 'Ambroxan', 'Bergamot', 'Eau de Parfum'] },
    { title: 'Lip Intensive', price: 1350, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800', rating: { rate: 4.8, count: 18000 }, description: 'Overnight berry lip mask with vitamin C, shea butter, and murumuru butter for intense hydration.', sizes: [], stock: 170, features: ['Berry Extract', 'Vitamin C', 'Shea Butter', 'Overnight Repair'] },
    { title: 'Sky High Lash', price: 799, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800', rating: { rate: 4.6, count: 110000 }, description: 'Volumizing mascara with flexible bamboo fiber brush, buildable formula, and up to 24-hour wear.', sizes: [], stock: 220, features: ['Bamboo Fiber', 'Buildable', '24hr Wear', 'Volumizing'] },
    { title: 'Hair Bonder', price: 2950, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800', rating: { rate: 4.7, count: 65000 }, description: 'Hair perfector treatment that repairs and strengthens broken bonds from within. No. 3 prep formula.', sizes: [], stock: 130, features: ['Bond Repair', 'No. 3 Formula', 'Strengthening', 'Pre-Treatment'] },
    { title: 'Blade Shave', price: 5495, category: 'Beauty & Personal Care', image: 'https://images.unsplash.com/photo-1629198726653-56d1eacbb8e0?w=800', rating: { rate: 4.8, count: 15000 }, description: 'Electric rotary shaver with self-sharpening blades, wet/dry use, 60-minute cordless runtime, and travel lock.', sizes: [], stock: 65, features: ['Self-Sharpening', 'Wet/Dry', '60min Runtime', 'Travel Lock'] },

    // ─── NEW PRODUCTS (imported from data files) ───
    ...newElectronics,
    ...newFootwear,
    ...newClothing,
    ...newAccessories,
    ...newFurniture,
    ...newSports,
    ...newHomeKitchen,
    ...newStationery,
    ...newBooksMedia,
    ...newBeauty,
    ...newToysGames,
    ...newAutomotive,
];

const importData = async () => {
    try {
        await Product.deleteMany();
        await User.deleteMany();

        await Product.insertMany(products);

        const salt = await bcrypt.genSalt(10);
<<<<<<< HEAD
        const adminHashedPassword = await bcrypt.hash('12345678', salt);
=======
>>>>>>> ac794f6acd6f07d555238c252853f4601e063236
        const hashedPassword = await bcrypt.hash('password123', salt);

        const users = [
            {
                name: 'Admin User',
<<<<<<< HEAD
                email: 'shopflow@gmail.com',
                password: adminHashedPassword,
=======
                email: 'admin@shop.com',
                password: hashedPassword,
>>>>>>> ac794f6acd6f07d555238c252853f4601e063236
                role: 'admin'
            },
            {
                name: 'Manager User',
                email: 'manager@shop.com',
                password: hashedPassword,
                role: 'manager'
            },
            {
                name: 'John Doe',
                email: 'user@shop.com',
                password: hashedPassword,
                role: 'user'
            }
        ];

        await User.insertMany(users);

        console.log(`Final Seed: ${products.length} Products and Default Users Created!`);
        process.exit();
    } catch (error) {
        console.error(`${error}`);
        process.exit(1);
    }
};

importData();
